describe('Adding a new blog and commenting it', function() {
  beforeEach(function() {
    cy.request('POST', 'http://localhost:9002/api/testing/reset')
    const user = {
      name: 'The Tester',
      username: 'tester',
      password: 'tester'
    }
    cy.request('POST', 'http://localhost:9002/api/users/', user)
    cy.visit('http://localhost:3000')
    cy.contains('log in')
      .click()
    cy.get('#username')
      .type('tester')
    cy.get('#password')
      .type('tester')
    cy.contains('login')
      .click()
    cy.contains('The Tester logged in')
  })

  it('Blog page can be found', function() {
    cy.get('#bloglink')
      .click()
  })

  it('A new blog can be added and commented', function() {
    cy.get('#bloglink')
      .click()
    cy.contains('add new blog')
      .click()
    cy.get('#title')
      .type('Adding a blog is such a fun thing')
    cy.get('#author')
      .type('Someone Funny')
    cy.get('#url')
      .type('http://how.fun.can.it.get')
    cy.contains('save')
      .click()
    cy.contains('Adding a blog is such a fun thing -- Someone Funny')
      .click()
    cy.contains('add new comment')
      .click()
    cy.get('#commentField')
      .type('Such a fun read as well!')
    cy.contains('save')
      .click()
  })

  it('A new blog can be added and liked', function() {
    cy.get('#bloglink')
      .click()
    cy.contains('add new blog')
      .click()
    cy.get('#title')
      .type('Just another blog')
    cy.get('#author')
      .type('Another One')
    cy.get('#url')
      .type('http://again.doing.it')
    cy.contains('save')
      .click()
    cy.contains('Just another blog -- Another One')
    cy.contains('->')
      .click()
    cy.contains('like')
      .click()
    cy.contains('likes: 1')
  })

  it('A new blog can be added and deleted', function() {
    cy.get('#bloglink')
      .click()
    cy.contains('add new blog')
      .click()
    cy.get('#title')
      .type('Feeling cute, might delete later')
    cy.get('#author')
      .type('Acute')
    cy.get('#url')
      .type('http://cute.or.not')
    cy.contains('save')
      .click()
    cy.contains('Feeling cute, might delete later -- Acute')
    cy.contains('->')
      .click()
    cy.get('#delete')
      .click()
    cy.contains('\'Feeling cute, might delete later\' blog has now been deleted')
  })

})